name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test model loading
      run: |
        python -c "import joblib; print('Joblib working')"
        python -c "import pandas as pd; print('Pandas working')"
        python -c "import sklearn; print('Sklearn working')"
    
    - name: Check model files exist
      run: |
        ls -la models/
        echo "Model files check completed"
